name: Python CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
        toxenv: [ django22, quality ]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements/base.txt
        pip install -r requirements/testing.txt
    
    - name: Run Pytest
      if: matrix.python-version == '3.8' && matrix.toxenv=='django22'
      run: make test-python

    - name: Run Quality Tests
      if: matrix.python-version == '3.8' && matrix.toxenv=='quality'
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='quality'
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true

