name: Python CI

on:
  push:
    branches:
      - master
      - cdodge/mcka-master
      - cdodge/notification-digest
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - 3.8
        toxenv: [ django22,quality ]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set display to virtual frame buffer
      run: export DISPLAY=:99.0



    - name: Install npm dependencies
      run: npm install

    - name: Install dependencies
      run: |
        pip install -r requirements/base.txt
        pip install -r requirements/testing.txt

    - name: Run Python and Quality Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Run Js/Bokchoy tests
      uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: '46.0'
        run: make test

    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='django22'
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
